# Site settings
title: Geckotree
email: hello@geckotree.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geckotree.co.uk" # the base hostname & protocol for your site

# Social media settings
twitter: geckotree
dribbble: geckotree
instagram: geckotree

# Blog settings
paginate: 2
paginate_path: "/blog/:num/"

# Build settings
markdown: kramdown
exclude: [ 
	"node_modules", 
	"bower.json", 
	"Gruntfile.js", 
	"package.json", 
	"README.md" 
]
